Save recipe offline
akp5896/RecipeApp pull request #44
Opened 2022-07-06 19:17 UTC by akp5896

Context: adding option to save recipe to device and view offline
Changes: added Room to store the recipe in SQL database. Also changed Recipe structure: added a custom deserializer instead of envelopes, to simplify structure and storage in room.
Here is also link to short walkthrough: https://imgur.com/a/1EnIuf1

2022-07-07 04:55 UTC, karangoel16 commented on app/src/main/java/com/example/recipeapp/DetailsActivity.java
> +        if(recipe.getAnalyzedInstructions() == null || recipe.getIngredients() == null) {
Let’s move this into view model

2022-07-08 21:46 UTC, karangoel16 commented on app/src/main/java/com/example/recipeapp/Fragments/FeedFragment.java
> +    public static FeedFragment newInstance(List<Recipe> recipes) {
discussed offline , lets provide view model and let it handle based on enum

2022-07-08 21:59 UTC, karangoel16 requested changes

2022-07-08 21:59 UTC, karangoel16 commented on app/src/main/java/com/example/recipeapp/viewmodels/DetailsViewModel.java
> +            handler.post(() -> bookmarkToast.setValue(R.string.recipe_bookmarked));
qq: why do we need setValue for bookmarkToast, do we need this value immediately, if not then we can simply use postValue

2022-07-08 21:59 UTC, karangoel16 commented on app/src/main/java/com/example/recipeapp/viewmodels/DetailsViewModel.java
> +            handler.post(() -> bookmarkToast.setValue(R.string.recipe_bookmarked));
ref - https://stackoverflow.com/questions/51299641/difference-of-setvalue-postvalue-in-mutablelivedata

2022-07-08 21:59 UTC, karangoel16 commented on app/src/main/java/com/example/recipeapp/viewmodels/DetailsViewModel.java
> +        });
nit:Maybe we can probably create repository , so that we do not need to create executor for all the database actions

2022-07-14 00:13 UTC, karangoel16 requested changes

2022-07-14 00:13 UTC, karangoel16 commented on app/src/main/java/com/example/recipeapp/Adapters/RecipesAdapter.java
> +        this.recipes.addAll(recipes);
https://blog.mindorks.com/the-powerful-tool-diff-util-in-recyclerview-android-tutorial

This might be more performant

2022-07-14 00:13 UTC, karangoel16 commented on app/src/main/java/com/example/recipeapp/Models/Recipe.java
> -        Call<Taste> call = service.getTasteById(id(), BuildConfig.API_KEY);
CMIIW, I think we built repositories for network calling.

2022-07-14 00:13 UTC, karangoel16 commented on app/src/main/java/com/example/recipeapp/ParseApplication.java
> +
nit: space

2022-07-14 00:13 UTC, karangoel16 commented on app/src/main/java/com/example/recipeapp/Retrofit/AutoValueGsonFactory.java
> +//}
can we remove this file if not needed

2022-07-14 00:13 UTC, karangoel16 commented on app/src/main/java/com/example/recipeapp/viewmodels/DetailsViewModel.java
> +//                    recipe.setIngredients(response.body().getIngredients());
nit: remove comments

2022-07-14 00:13 UTC, karangoel16 commented on app/src/main/java/com/example/recipeapp/viewmodels/DetailsViewModel.java
> +//                    recipe.setAnalyzedInstructions(response.body().getAnalyzedInstructions());
Lets use Repository for this

2022-07-18 16:23 UTC, akp5896 commented on app/src/main/java/com/example/recipeapp/Models/API/ApiCallParams.java
> +public class ApiCallParams {
Yes, but I'm passing it a couple of times, from Search to SearchFeed, to viewmodel and to a repo. Not sure if it's possible to shorten it?

2022-07-28 16:47 UTC, merged